import {
  ico_ru,
  ico_mat,
  ico_eng,
  ico_glob,
  ico_lit,
  ico_litch,
  ico_biology,
  ico_chemistry,
  ico_history,
  ico_informatic,
  ico_geom,
  ico_physics,
  ico_society,
  ico_muz,
  ico_ris,
} from "../../shared/Images/index";
export const lessonMap = {
  1: [
    { title: "Русский язык", img: ico_ru },
    { title: "Математика", img: ico_mat },
    { title: "Литературное чтение", img: ico_litch },
    { title: "Окружающий мир", img: ico_glob },
  ],
  2: [
    { title: "Русский язык", img: ico_ru },
    { title: "Математика", img: ico_mat },
    { title: "Литература", img: ico_lit },
    { title: "Окружающий мир", img: ico_glob },
    { title: "Английский язык", img: ico_eng },
  ],
  3: [
    { title: "Русский язык", img: ico_ru },
    { title: "Математика", img: ico_mat },
    { title: "Литература", img: ico_lit },
    { title: "Окружающий мир", img: ico_glob },
    { title: "Английский язык", img: ico_eng },
  ],
  4: [
    { title: "Русский язык", img: ico_ru },
    { title: "Математика", img: ico_mat },
    { title: "Литература", img: ico_lit },
    { title: "Окружающий мир", img: ico_glob },
    { title: "Английский язык", img: ico_eng },
  ],
  5: [
    { title: "Русский язык", img: ico_ru },
    { title: "Математика", img: ico_mat },
    { title: "Литература", img: ico_lit },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
  ],
  6: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Информатика", img: ico_informatic },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
  7: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Химия", img: ico_chemistry },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Физика", img: ico_physics },
    { title: "Геометрия", img: ico_geom },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
  8: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Химия", img: ico_chemistry },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Физика", img: ico_physics },
    { title: "Геометрия", img: ico_geom },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
  9: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Химия", img: ico_chemistry },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Физика", img: ico_physics },
    { title: "Геометрия", img: ico_geom },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
  10: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Химия", img: ico_chemistry },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Физика", img: ico_physics },
    { title: "Геометрия", img: ico_geom },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
  11: [
    { title: "Русский язык", img: ico_ru },
    { title: "Алгебра", img: ico_mat },
    { title: "Химия", img: ico_chemistry },
    { title: "История", img: ico_history },
    { title: "Биология", img: ico_biology },
    { title: "Информатика", img: ico_informatic },
    { title: "Английский язык", img: ico_eng },
    { title: "География", img: ico_glob },
    { title: "Физика", img: ico_physics },
    { title: "Геометрия", img: ico_geom },
    { title: "Обществознание", img: ico_society },
    { title: "Литература", img: ico_lit },
  ],
};

export const priceMap = {
  "1-4": "12 500р",
  "5-8": "12 500р",
  "9-11": "12 500р",
};

export const secondaryLessons = [
  { title: "Музыка", img: ico_muz },
  { title: "Рисование", img: ico_ris },
];
