export { default as logo } from "./logoHeader.png";
export { default as license } from "./ic_license.png";
export { default as vk } from "./ic_vk.png";
export { default as tg } from "./ic_tg.png";
export { default as youtube } from "./ic_youtube.png";
export { default as place } from "./ic_place.png";
export { default as phone } from "./ic_tel.png";
export { default as tg_40 } from "./ic_tg_40.png";
export { default as watsapp } from "./ic_watsapp.png";
export { default as background } from "./background.png";
export { default as group } from "./Group.png";
export { default as ico_cond_1 } from "./ico_cond_1.png";
export { default as ico_cond_2 } from "./ico_cond_2.png";
export { default as ico_cond_3 } from "./ico_cond_3.png";
export { default as ico_cond_4 } from "./ico_cond_4.png";
export { default as ico_cond_5 } from "./ico_cond_5.png";
export { default as promo_girl } from "./cond_girl.png";
export { default as cond_aspect_1 } from "./cond_aspect_1.png";
export { default as cond_aspect_2 } from "./cond_aspect_2.png";
export { default as cond_aspect_3 } from "./cond_aspect_3.png";
export { default as cond_aspect_4 } from "./cond_aspect_4.png";
export { default as advant_img } from "./advant_img.png";
export { default as advant_2 } from "./advant_2.png";
export { default as advant_3 } from "./advant_3.png";
export { default as advant_vector } from "./advant_vector.png";
export { default as comparison_1 } from "./comparison_1.png";
export { default as comparison_2 } from "./comparison_2.png";
export { default as benefits_1 } from "./benefits_1.png";
export { default as benefits_2 } from "./benefits_2.png";
export { default as benefits_3 } from "./benefits_3.png";
export { default as benefits_4 } from "./benefits_4.png";
export { default as benefits_5 } from "./benefits_5.png";
export { default as benefits_6 } from "./benefits_6.png";
export { default as promo_boy } from "./promo_boy.png";
export { default as price_girl_1 } from "./price_girl_1.png";
export { default as price_girl_2 } from "./price_girl_2.png";
export { default as price_girl_3 } from "./price_girl_3.png";
export { default as price_ico } from "./price_ico.png"; 
export { default as sertificate} from "./sertificate.png"; 
export { default as placeholder_1} from "./placeholder_1.png"; 
export { default as placeholder_2} from "./placeholder_2.png";
export { default as placeholder_3} from "./placeholder_3.png";  
export { default as reviews_1} from "./reviews_1.png";  
export { default as slider_vk} from "./slider_vk.png";  
export { default as slider_inst} from "./slider_inst.png"; 
export { default as bg_reviews} from "./bg_reviews.png";
export { default as application_img} from "./application_img.png";
export { default as bg_form} from "./bg_form.png";
export { default as promo_1to4 } from "./promo_1to4.png";
export { default as promo_5to8 } from "./promo_5to8.png";
export { default as promo_9to11 } from "./promo_9to11.png";
export { default as ico_prog1 } from "./ico_prog1.png";
export { default as ico_prog2 } from "./ico_prog2.png";
export { default as ico_prog3 } from "./ico_prog3.png";
export { default as progr__comp } from "./progr_comp.png";
export { default as ico_ru } from "./ico_less_ru.png";
export { default as ico_mat } from "./ico_less_mat.png";
export { default as ico_eng } from "./ico_less_eng.png";
export { default as ico_glob } from "./ico_less_glob.png";
export { default as ico_lit } from "./ico_less_lit.png";
export { default as ico_litch } from "./ico_less_litch.png";
export { default as ico_muz } from "./ico_lees_muz.png";
export { default as ico_ris } from "./ico_less_ris.png";


